---
- hosts: web
  become_user: "{{ deploy_user }}"

  vars_files:
    - app-vars.yml

  pre_tasks:
    - name: Setup app folder
      file:
        state: directory
        path: "{{ app_root_path }}"
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"

    - name: Copy rbenv-vars file
      template:
        src: ".rbenv-vars.j2"
        dest: "{{ app_root_path }}/.rbenv-vars"
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"

    - name: Make shared directories
      file: 
        path: "{{ app_shared_path }}/{{ item }}" 
        state: directory
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"
      with_items:
        - tmp
        - tmp/pids
        - tmp/cache
        - sockets
        - log
        - public
        - public/packs
        - vendor
        - vendor/bundle
        - bin
        - config
        - config/puma
        - assets
        - node_modules

  tasks:

    - name: check host exists
      ansible.builtin.ping:

    - name: nginx
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/conf.d/{{ app_name }}.conf"
  
  roles: 
    - role: postgresql
      tags: postgresql

- hosts: local
  tasks:
    - name: Creates github directory
      file:
        path: "{{ playbook_dir }}/.github/workflows"
        state: directory
    - name: gh action
      copy:
        src: setup.yml
        dest: "{{ playbook_dir }}/.github/workflows/deploy.yml"
